### PR TITLE
Refactors Rcpp -> cpp11

### PR DESCRIPTION
**Pull request by pachadotdev**
Hi @jeroen 

I refactored the C++ to be able to use vendoring and install this in a restricted server at my university. I hope this PR helps and can be merged, it brings some minor speedups but those are not really important.

Best,

### CODE REVIEW

**Comment by jeroen** [comment]
What problem does this solve? Why cant you install this in your university currently?

**Comment by pachadotdev** [comment]
> What problem does this solve? Why cant you install this in your university currently?

everything has to pass IT verification, so we vendor everything to minimize paperwork

the other thing is that this PR leads to another branch where I got it to work with tessearct 5 https://github.com/pachadotdev/tesseract/tree/tesseract5

**Comment by jeroen** [comment]
This PR does too many things. The current version already works with Tesseract 5 so I am not sure what problem this solves. I don't see any benefit of switching to cpp11. 

If you are missing a particular feature, such as downloading different training data by default, could you create a as-small-as-possible PR with only this feature?

**Comment by pachadotdev** [comment]
> This PR does too many things. The current version already works with Tesseract 5 so I am not sure what problem this solves. I don't see any benefit of switching to cpp11.
> 
> If you are missing a particular feature, such as downloading different training data by default, could you create a as-small-as-possible PR with only this feature?

I tried to clone the repo and install the package with Tesseract 5, and then `devtools::install()` fails unless I revert to Tesseract 4.

About the cpp11, it is a niche thing. I can modify one line in the DESCRIPTION and vendor cpp11 to install this in a cluster that is super restricted.

I shall send you a small PR for the best models.

**Comment by pachadotdev** [comment]
@jeroen is it ok if I keep a fork of this PR under a different name (i.e., "cpp11tesseract")

**Comment by pachadotdev** [comment]
reorganized by type into #64 #65 #66

**Pull request closed without merging**
