### PR TITLE
fix #67

### LINKED ISSUE #67: comparison of different sizes
I still cannot install it in the clusterm, but I tried in my laptop and after updating Rcpp to 1.0.13 it works but it gives me a warning

```
tesseract.cpp: In function ‘Rcpp::List engine_info_internal(TessPtr)’:
   tesseract.cpp:115:23: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
     115 |   for(size_t i = 0; i < langs.size(); i++)
         |                     ~~^~~~~~~~~~~~~~
   tesseract.cpp:120:23: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
     120 |   for(size_t i = 0; i < langs.size(); i++)
         |                     ~~^~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by pachadotdev**

### CODE REVIEW

**Comment by jeroen** [comment]
We can probably fix the warning by using `int i` instead of `size_t i` in the for loop.

**Comment by pachadotdev** [comment]
> We can probably fix the warning by using `int i` instead of `size_t i` in the for loop.

I edited that!

it is practically the same, the number of languages will never create an integer overflow and that the performance impact is zero

**Comment by jeroen** [comment]
I meant that that way you can keep the `langs.size()` in the loop and keep the diff very minimal.

**Comment by pachadotdev** [comment]
> I meant that that way you can keep the `langs.size()` in the loop and keep the diff very minimal.

yes, my PR saves 1 duplicated computation

**Comment by jeroen** [comment]
Can you fix the merge conflict

**Comment by pachadotdev** [comment]
> Can you fix the merge conflict

done, thx!

**Pull request merged**
